version: "3.3"
services:
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025" # smtp server
      - "8029:8025" # web ui
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbtopmed
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./database:/initialize
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3008:3008"
    depends_on:
      - db
    volumes:
      - backend:/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - frontend:/src
volumes:
  database:
  backend:
  frontend:
